### ISSUE TITLE
Is there a possibility to call Splunk Cloud Rest API using this code.

### ISSUE THREAD

**Issue by sumang99** [harsmarvania57/splunk-ko-change#6]
Great coding. I have tried your code on a sandbox local on standalone box and it worked absolutely fine. But I would like to implement this for an Splunk cloud instance using an on-prem server. When I tried updating the endpoint code and providing the username and password it's returning with auth issues.  Can give an advice on how to fix that and make it to work with Splunk Cloud. Appreciate your time and help. Thank you!

**Comment by harsmarvania57** [comment]
You can use same script to change KO permission in SplunkCloud, only requirement is you need Splunk Enterprise on local instance on which you are running this python script because it is using Python libraries which is shipped in Splunk Enterprise.

For example: In below example replace <stack> with your SplunkCloud stack.
`[splunk@splunkserver01 etc]$ /opt/splunk/bin/splunk cmd python ko_change.py list savedsearch --user admin --host <stack>.splunkcloud.com`

**Comment by sumang99** [comment]
Thanks for the rapid response. Really appreciate that. When i'm trying with Splunk Cloud I'm getting this below errors. I did test the connectivity from local splunk server to cloud using curl command.  
Ex: curl -k -u admin:password https://dev-companyname.splunkcloud.com:8089/servicesNS/-/-/data/lookup-table-files
Note: admin user is local and have restapi capabilities and admin capabilities.   

Outcome after execution:
bash-4.2$ /opt/splunk/bin/splunk cmd python /opt/splunk/splunk-ko-change/ko_change.py list savedsearch --user a154960 --host dev-companyname.splunkcloud.com
Enter username with admin privileges: restapi_test
Enter password:
Socket error communicating with splunkd (error=timed out), path = /services/auth/login
Traceback (most recent call last):
  File "/opt/splunk/lib/python3.7/site-packages/splunk/rest/__init__.py", line 515, in simpleRequest
    serverResponse, serverContent = h.request(uri, method, headers=headers, body=payload)
  File "/opt/splunk/lib/python3.7/site-packages/httplib2/__init__.py", line 1959, in request
    cachekey,
  File "/opt/splunk/lib/python3.7/site-packages/httplib2/__init__.py", line 1622, in _request
    conn, request_uri, method, body, headers
  File "/opt/splunk/lib/python3.7/site-packages/httplib2/__init__.py", line 1528, in _conn_request
    conn.connect()
  File "/opt/splunk/lib/python3.7/site-packages/httplib2/__init__.py", line 1309, in connect
    sock.connect((self.host, self.port))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/splunk/splunk-ko-change/ko_change.py", line 552, in <module>
    main()
  File "/opt/splunk/splunk-ko-change/ko_change.py", line 486, in main
    session_key = user_check(ko_type)
  File "/opt/splunk/splunk-ko-change/ko_change.py", line 103, in user_check
    session_key = auth.getSessionKey(username, password)
  File "/opt/splunk/lib/python3.7/site-packages/splunk/auth.py", line 37, in getSessionKey
    serverResponse, serverContent = rest.simpleRequest(uri, postargs=args)
  File "/opt/splunk/lib/python3.7/site-packages/splunk/rest/__init__.py", line 523, in simpleRequest
    raise splunk.SplunkdConnectionException('Error connecting to %s: %s' % (path, str(e)))
splunk.SplunkdConnectionException: Splunkd daemon is not responding: ('Error connecting to /services/auth/login: timed out',)

Any thoughts?

**Comment by harsmarvania57** [comment]
This looks like connectivity issue from your local instance to splunk cloud because I am able to retrieve content from splunkcloud instance on which I have local user with sc_admin role.

**Comment by sumang99** [comment]
Good to know. I gave all the capabilities to a custom role and assigned it to the local user. Can you tell me which port this script is using to connect to Splunk cloud is it 8089 or the web port or something else? Also our cloud instance is Clustered does it make any difference?

**Comment by harsmarvania57** [comment]
Script is using 8089 port. If your cloud instance is SH clustered then you just need to change config on only one SHC member and SHC will automatically replicate it to other SHC members.

**Comment by sumang99** [comment]
Thanks for the above answers. I can't establish the connection cloud yet. Do you've some code recommendation on how to use token authentication instead of the session key in splunk-ko-change.py?

Really appreciate your time and help.

**Comment by harsmarvania57** [comment]
Released new version, please download latest release which includes token authentication.

**Comment by sumang99** [comment]
I have Tried using your code "Auth Token" and got the authentication success to Cloud to pull the savedsearch info but when I tried using it for ownership change it's failing again. Tested it on Local instance/on-prem/Splunk cloud it's only able pull the KO list but ownership change is not working with Auth Token. 
Getting below error message after running this command.
/opt/splunk/bin/splunk cmd python /home/splunk/ownerchange.py change savedsearch --olduser bravo --newuser charlie
Authentication method:
1.) Username and Password
2.) Auth token
Please select authentication method (Enter 1 or 2): 2
Enter token:
Traceback (most recent call last):
  File "splunkko.py", line 560, in <module>
    main()
  File "splunkko.py", line 501, in main
    session_key = user_check(ko_type, new_owner)
  File "splunkko.py", line 116, in user_check
    userlist = auth.getUser(name=new_owner)
  File "/opt/splunk/lib/python3.7/site-packages/splunk/auth.py", line 121, in getUser
    info = en.getEntity(uri, name, **kwargs)
  File "/opt/splunk/lib/python3.7/site-packages/splunk/entity.py", line 277, in getEntity
    serverResponse, serverContent = rest.simpleRequest(uri, getargs=kwargs, sessionKey=sessionKey, raiseAllErrors=True)
  File "/opt/splunk/lib/python3.7/site-packages/splunk/rest/__init__.py", line 553, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated

**Comment by harsmarvania57** [comment]
Release 1.2.4 has fix for this error, please download latest release.

**Comment by sumang99** [comment]
Wow you're so proactive with your response and new releases. Greatly, Appreciate all your help and support.
