### ISSUE TITLE
Issue running list for specific objects category for all the users.

### ISSUE THREAD

**Issue by sumang99** [harsmarvania57/splunk-ko-change#7]
When running view selected knowledge object owned by any user command in any instance we're getting "no savedsearch found" even though we've savedsearches which is searched by specific user. It the same behaviour across any instance local/standalone/SHC. 

## /opt/splunk/bin/splunk cmd python ./ko_change.py list savedsearch --file ./savedsearch.txt

**Comment by harsmarvania57** [comment]
Are you trying to list knowledge object from local instance or remote instance? Also what is the content in "savedsearch.txt" file?

**Comment by sumang99** [comment]
![image](https://user-images.githubusercontent.com/93281934/141832186-5aba740f-1f34-4ec6-aadc-56ddd51707e1.png)
I have tried it on local and remote machine same issue in both the places.

**Comment by sumang99** [comment]
Apologies on the wrong interpretation. I was doing this in a wrong why I have not content in the file. 
Is there a way to pull all the knowledge objects and write to a file using the script?

**Comment by harsmarvania57** [comment]
Not using this script but you can pull out knowledge object, using REST searches ( `| rest ....`). I am closing this issue because it was wrong interpretation between --user and --file options.
